# Generated by Django 3.0.3 on 2020-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='intro',
            field=models.CharField(default='Needs an Intro', max_length=100),
        ),
    ]
