# Generated by Django 3.0.3 on 2020-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='Enter category Here...', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='weblink',
            field=models.CharField(default='Enter Url Here...', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='intro',
            field=models.CharField(default='Enter Intro Here...', max_length=100),
        ),
    ]
